import axios from 'axios';
import Head from 'next/head'
import {Head as HeadDoc} from 'next/document'
import Image from 'next/image'
import { useEffect } from 'react'
import Card from '../components/Card';
import Header from '../components/Header';
import styles from '../styles/Home.module.css'

export default function Home() {
  // useEffect(() => {
  //   axios.get('/api/connectDB').then(res => {
  //     console.log(res.data.message);
  //   }).catch(err => {
  //     console.log(err);
  //   })
  // }, []);

  const handleClick = () => {
    axios.post('/api/test_db', {
      name: 'Transaction 08/07/2022 Test Called second',
      price: '$10000',
      description: 'This is a test transaction',
      imageUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
      created_at: '2020-01-01'
    }, {headers: {'Content-Type': 'application/json'}}).then(res => {
      console.log(res.data);
    }).catch(err => {
      console.log(err);
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Katalog | Kantin Kejujuran</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header/>
        <div className={styles.header_title}>
          <h1>Item Tersedia</h1>
          <button className={styles.primary_button}>+ Tambah item</button>
        </div>
        <div className={styles.grid}>
          <Card/>
          <Card/>
          <Card/>
          <Card/>
          <Card/>
          <Card/>
        </div>
        <button onClick={handleClick}>test db</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
