import axios from 'axios';
import React from 'react';
import Header from '../../components/Header';
import styles from '../../styles/Home.module.css'
import Head from 'next/head'
import transaction from '../../styles/Transaction.module.css'

export default function Transaction() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Balance &amp; Riwayat Transaksi | Kantin Kejujuran</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet'/>
      </Head>

      <div className={styles.main}>
        <Header/>
        <div className={styles.header_title}>
          <h1>Balance &amp; Riwayat transaksi</h1>
        </div>
        <div className={styles.grid}>
          <div className={transaction.balance_withdrawl}>
            <div className={transaction.balance}>
              <p className={transaction.title}>Balance</p>
              <div className={transaction.balance_info}>
                <h1>Rp. 1.000.000</h1>
              </div>
            </div>
            <div className={transaction.withdrawl}>
              <button className={styles.primary_button}>+ Withdrawl</button>
            </div>
          </div>
          <div className={transaction.transaction_hist}>
            <p className={transaction.title}>Riwayat transaksi</p>
            <div className={transaction.list_transaction_hist}>
              <div className={transaction.transaction_tile}>
                <div className={transaction.transaction_tile_info}>
                  <h2>Pembelian X oleh Y</h2>
                  <p>01 Jan 1970</p>
                </div>
                <div className={transaction.value}>
                  <h2>Rp10.000,00</h2>
                </div>
              </div>

              <div className={transaction.transaction_tile}>
                <div className={transaction.transaction_tile_info}>
                  <h2>Pembelian X oleh Y</h2>
                  <p>01 Jan 1970</p>
                </div>
                <div className={transaction.value}>
                  <h2>Rp10.000,00</h2>
                </div>
              </div>

              <div className={transaction.transaction_tile}>
                <div className={transaction.transaction_tile_info}>
                  <h2>Pembelian X oleh Y</h2>
                  <p>01 Jan 1970</p>
                </div>
                <div className={transaction.value}>
                  <h2>Rp10.000,00</h2>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}